import {readFileSync,writeFileSync} from 'node:fs';
const assets={};
for(const [file,type]of [['index.html','text/html; charset=utf-8'],['admin.css','text/css; charset=utf-8'],['admin.js','text/javascript; charset=utf-8'],['image-processing.js','text/javascript; charset=utf-8']])assets['/admin/'+file]={body:readFileSync('public/admin/'+file,'utf8'),type};
writeFileSync('worker/admin-assets.js','// Generated by tools/build_admin_assets.mjs; not served without authentication.\nexport const adminAssets = '+JSON.stringify(assets)+';\n');