"""Generate a deterministic site from the catalog, then fingerprint assets."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
PUBLIC = ROOT / 'public'

def normalize_text():
    # Hash identical bytes on Windows previews and Linux production builds.
    for path in PUBLIC.rglob('*'):
        if path.is_file() and path.suffix.lower() in {'.html', '.js', '.css', '.json', '.xml', '.txt', '.svg'} and 'products_raw' not in path.parts:
            raw = path.read_bytes()
            clean = raw.replace(b'\r\n', b'\n')
            if clean != raw:
                path.write_bytes(clean)

def run(script, *args):
    subprocess.run([sys.executable, str(ROOT / 'tools' / script), *args], check=True, cwd=ROOT)

def build():
    normalize_text()
    products = json.loads((PUBLIC / 'data/products.json').read_text(encoding='utf-8'))
    categories = json.loads((PUBLIC / 'data/categories.json').read_text(encoding='utf-8'))
    (PUBLIC / 'js/data.js').write_text('// Generated by tools/build_release.py; edit public/data/products.json instead.\nwindow.KANAPET_PRODUCTS = ' + json.dumps(products, ensure_ascii=False, indent=2) + ';\nwindow.KANAPET_CATEGORIES = ' + json.dumps(categories, ensure_ascii=False, indent=2) + ';\n', encoding='utf-8')
    run('sync_product_output.py')
    if (ROOT / 'tools/build_insights.py').is_file():
        run('build_insights.py')
    run('normalize_accessibility.py')
    normalize_text()
    for page in PUBLIC.rglob('*.html'):
        source = page.read_text(encoding='utf-8')
        def version(match):
            asset = PUBLIC / match.group(2).lstrip('/')
            if not asset.is_file():
                raise ValueError(f'Missing asset {asset}')
            digest = hashlib.sha256(asset.read_bytes()).hexdigest()[:12]
            return match.group(1) + match.group(2) + '?v=' + digest + match.group(3)
        updated = re.sub(r'((?:src|href)=")(/?(?:js|css)/[^"?]+\.(?:js|css))(?:\?[^" ]*)?(")', version, source)
        if updated != source:
            page.write_text(updated, encoding='utf-8')
    normalize_text()
    files = {}
    for path in sorted(PUBLIC.rglob('*')):
        if path.is_file() and 'products_raw' not in path.parts and 'admin' not in path.parts and path.name not in {'release.json', '.assetsignore'}:
            files[path.relative_to(PUBLIC).as_posix()] = hashlib.sha256(path.read_bytes()).hexdigest()
    release_id = hashlib.sha256(json.dumps(files, sort_keys=True).encode()).hexdigest()[:16]
    (PUBLIC / 'release.json').write_bytes((json.dumps({'id': release_id, 'files': files}, sort_keys=True, indent=2) + '\n').encode('utf-8'))
    print('Release:', release_id)

if __name__ == '__main__':
    build()
